### ISSUE TITLE
UTRS has suffered an internal exception and can't continue to serve your request

### ISSUE THREAD

**Issue by PatrickJYKang** [UTRS2/utrs#568]
<img width="845" alt="Screenshot 2022-06-25 132307" src="https://user-images.githubusercontent.com/87932092/175759582-cffe8902-43f3-4eb7-8a04-e7b812cdcf3a.png">

**Comment by mondilla9292** [comment]
How do i get out of this bug.

**Comment by Salvidrim** [comment]
I was able to successfully create a block appeal ticket on UTRS for my blocked account, so the issue does not appear to be a universal "nothing works at all" problem.

Are you able to provide a bit more information about where you encountered this error, what were you trying to do, what step of the appeal process were you at, what data was entered, etc. to assist the developper in troubleshooting?

**Comment by mondilla9292** [comment]
I was trying to create a Wikipedia account almost. And when i entered my
email address to sign up i saw this error saying my IP address is blocked.

**Comment by Rombobeorn** [comment]
I got this error today. This is the data I entered:

What wiki are you blocked on?
Global locks/blocks

What is your username?
Rombobjörn

Is your account directly blocked?
No, the underlying IP address is blocked

If you selected "No, the underlying IP address is blocked" above, what is the blocked IP?
2a00:1a28:1410:5::10db

Why should you be unblocked?
"Sometimes I want to correct an error or make some other minor improvement to the Swedish or English Wikipedia or Wiktionary. Before I can do that I have to disable IPv6 to get around this address blocking. This means additional trouble that makes the motivation threshold much higher, and decreases the number of contributions from me. Although I'm not among the more prolific editors, perhaps my editing history shows that I've been well-behaved enough to be allowed to contribute without messing with my network configuration?

The eight addresses 2a00:1a28:1410:5::10d8 to 2a00:1a28:1410:5::10df are mine for as long as I rent them. They are part of a 32-bit prefix that is blocked with the motivation "no open proxies". I suppose there may be some proxies among those 2^96 addresses, but not on mine. I use my eight IPv6 addresses to communicate with the 21st century Internet. Without them I'd be restricted to IPv4 because most purported Internet service providers in Sweden are only IPv4 service providers, stuck in the 1990s.

I think the best solution would be if my user account could be exempted from IP address blocking. I have no particular reason to not log in when contributing. If you prefer to split the block into two to unblock my eight addresses, that should also work for me for now."


In my first attempt I wrote "2a00:1a28:1410:5::10d8 to 2a00:1a28:1410:5::10df" in the IP address field and got the error "The hiddenip must be a valid IP address.". Then I changed it to a single address, submitted again, and got the same error as PatrickJYKang above. Thus I may or may not have filed an appeal, but I got no appeal key.

**Comment by Salvidrim** [comment]
It seems there might be an issue with trying to file an appeal for a global IPv6 rangeblock. I don't know if the issue is because it is a global vs. local rangeblock, or because it is IPv6 vs. IPv4, or rangeblock vs. IP block. Our devs will have to look into that.

This specific rangeblock is on 2a00:1a28::/32 https://meta.wikimedia.org/w/index.php?title=Special:Log&page=User%3A2A00%3A1A28%3A0%3A0%3A0%3A0%3A0%3A0%2F32&type=block

In the meantime @Rombobeorn you can follow the instructions on [Meta Wikimedia's Global Blocks FAQ](https://meta.wikimedia.org/wiki/Global_blocks/FAQ#Right,_but_I_don't_know_why_I've_been_blocked._Can_you_help_me?) to contact the Stewards team and request Global IP Block Exemption (IPBE), or yes indeed you will have to disable your IPv6 range to edit, as the IPs are blocked as belonging to cloud webhost GleSYS AB

**Comment by Salvidrim** [comment]
To test, I just tried filing an underlying-IP-is-blocked appeal for "Global locks/blocks", I tried to input the blocked IP range a few different ways:

- The shorthand blocked range **2a00:1a28::/32** -> error "The hiddenip must be a valid IP address." and returns to appeal form
- The longform blocked range **2A00:1A28:0:0:0:0:0:0/32**  -> error "The hiddenip must be a valid IP address." and returns to appeal form
- The base IP of the blocked range **2A00:1A28:0:0:0:0:0:0** -> error which does not return to appeal form, "Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request." as screenshotted above

**Comment by BigChungus1009** [comment]
I just got this error. I can't tell if it is my ip address or the fact that I'm connected via mobile network. Either way I found out I got banned yesterday and am trying to appeal. I haven't been able to open a new request yet.

**Comment by MarcoAurelioWM** [comment]
I can reproduce this while testing the system for `Global locks/blocks`, account `MarcoAurelio (test 2)`. It repeatedly tells me that `Uh-oh. UTRS has suffered an internal exception and can't continue to serve your request`. No appeal key given or generated.

**Comment by dqwiki** [comment]
I fixed an issue with the global locking system where the API had changed.
Relevant patches: 5facbcdfd1d74437d26c0d91d66594fe7f164745 9e29f52b1ac40b0cfefc48806807e03edfccc1ce

Please let me know if there are anymore issues, but I used MA's username as a test and it worked.

**Comment by Westlander11** [comment]
The issue has started up again for me...

**Comment by Westlander11** [comment]
I was trying to make an appeal for my account which was falsely accused of "sockpuppeting" someone I don't know on Wikipedia.
Username: Westwind51000
